
<u>Recall</u>:
Exceptions
3. let your caller catch it.
```c++
int f() {
	vector v;
	v.push_back(1);
	v.at(1);
}

int g() {
	try {f();}
	catch (range-error &r) {
		// do something
	}
}
```
Exception will <u>propagate</u> back through the call chain until a handler is found.
- called <u>unwinding</u> the stack.
- If no handler found, program aborts.
- Control resumes after the catch block. (Problem code is not retried)

What happens if a constructor throws an exception?
- Object is considered partially constructed.
- Destructor will not run on partially constructed objects.

<u>Example</u>:
```c++
class C {...};
class D {
	C a;
	C b;
	int *c;
public:
	D() {
		c = new int[10];
		...
		if (...) throw some thing; //*
	}
	~D() {
		delete [] c;
	}
};

D d;
```
At `*`, the D object is not fully constructed, so `~D()` will not run on d.
But - a and b <u>are</u> fully constructed, so their destructors <u>will</u> run.
So if a constructor wants to throw, it must clean up after itself.
```c++
D() {
	c = new int[10];
	...
	if (...) {
		delete [] c;
		throw something;
	}
}
```


What happens if a destructor throws? <u>Trouble</u>
- By default - program aborts <u>immediately</u>. `std::terminate` is called.
- If you really want a throwing destructor, tag it with `noexcept(false)`
- But watch out ...
```c++
class myexn{};
class C {
	...
public:
	~C() noexcept(false) {
		throw myexn{};
	}
};

void h() {
	C c1; 
	// destructor for c1 throws at the end of h
}

void g() {
	C c2;
	h();
	// unwind through g
	// destructor for c2 throws as we leave g.
}

void f() {
	try {
		g();
	}
	catch(myexn &exn) {
		...
	}
}
```
- no handler yet
- now <u>2</u> unhandled errors.
- <u>immediate</u> termination guaranteed.

<u>Never</u> let destructors throw. Swallow the exceptions if necessary.

<u>Also Note</u>: you can throw any value - not just objects.





# Problem 12: But I wanted a vector of chars ...
Start over? - No.
Introduce a major abstraction mechanism - *templates*- generalize over types
```c++
// vector.cc
export module vector;
namespace cs246e {

export template <typename T> class vector {
	size_t n, cap;
	T * theVector;
public:
	vector();
	... 
	void push_back(T n);
	T &operator[](size_t i);
	const T &operator[](size_t i) const;
	using iterator = T*;
	using const_iterator = const T*;
};

template <typename T> vector<T>::vector(): 
	n{0}, cap{1}, theVector{new T[cap]} {}

template <typename T> void vector<T>::push_back(T n) {
	...
}
...
}
```
<u>Note:</u> mush put implementation in interface file.
```c++
// main.cc
int main() {
	cs246e::vector<int> v; // vector of ints
	v.push_back(1);
	...
	cs246e::vector<char> w; // vector of chars
	w.push_back('a');
	...
}
```

<u>Semantics</u>: The first time the compiler encounters `vector<int>`, it creates a version of vector's code, where int replaces T, and compiles the new class.
Similarly for `vector<char>`.




# Problem 13: Where do I even start?

Long sequence of push_backs is chunky.
	Arrays: `int a[] = {1, 2, 3, 4, 5}` :)
	Vectors: `vector v; v.push_back(1); ...` :^(

<u>Goal: better initialization</u>
```c++
template <typename T> class vector {
	...
public:
	vector(): ... {}
	vector(size_t n, T x = T{}): 
		n{n}, cap{n == 0? 1 : n}, theVector{new T[cap]} {
		for (size_t i = 0; i < n; ++i) {
			theVector[i] = x;
		}
	}
}
```
<u>Now:</u>
```c++
vector<int> v; //empty
vector<int> w {5}; // 0 0 0 0 0
```
<u>Note</u>:
`T{}` (default constructor) means 0 if T is a built-in type
